import React from 'react'

export function CardProduct() {
  return (
    <div className="mx-auto grid max-w-2xl grid-cols-1 justify-between gap-6 text-sm sm:mt-20 sm:grid-cols-2 md:gap-y-10 lg:max-w-none lg:grid-cols-2">
      <div className="flex flex-col rounded-lg bg-white shadow-sm shadow-gray-100 md:max-w-xl md:flex-row">
        <img
          className=" h-96 w-full rounded-t-lg object-cover md:h-auto md:w-48 md:rounded-none md:rounded-l-lg"
          src="https://images.unsplash.com/photo-1530679361860-63f81c6e9268?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80"
          alt=""
        />
        <div className="flex flex-col justify-start p-6">
          <h5 className="mb-2 text-xl font-medium text-gray-900">
            Crash / Boom Indices
          </h5>
          <p className="mb-4 text-start text-base text-gray-700">
            These indices observe an average of one drop (crash) or one spike
            (boom) in prices every 100 ticks.
          </p>
        </div>
      </div>

      <div className="flex flex-col rounded-lg bg-white shadow-sm shadow-gray-100 md:max-w-xl md:flex-row">
        <img
          className="h-96 w-full rounded-t-lg object-cover md:h-auto md:w-48 md:rounded-none md:rounded-l-lg"
          src="https://images.unsplash.com/photo-1609790259520-cf7bce1bad5e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=686&q=80"
          alt=""
        />
        <div className="flex flex-col justify-start p-6">
          <h5 className="mb-2 text-xl font-medium text-gray-900">
            Volatility Indices
          </h5>
          <p className="mb-4 text-start text-base text-gray-700">
            These indices are generated by in-house models to mimic the real
            market with constant volatilities of 10% and 25%.
          </p>
        </div>
      </div>
    </div>
  )
}
