import React from 'react'
import CrashImage from '@/images/crash.jpg'
import VolatilityImage from '@/images/volatility.jpg'

export function CardProduct() {
  return (
    <div
      id="card-main"
      className="mx-auto grid max-w-2xl grid-cols-1 justify-between gap-6 text-sm sm:mt-20 sm:grid-cols-2 md:max-w-none md:grid-cols-2 md:gap-y-10 lg:max-w-none lg:grid-cols-2"
    >
      <div
        id="card-crash"
        className="flex flex-col rounded-lg bg-white shadow-black drop-shadow-2xl md:max-w-xl md:flex-row"
      >
        <img
          id="crash-image"
          className=" h-96 w-full rounded-t-lg object-cover md:h-auto md:w-48 md:rounded-none md:rounded-l-lg"
          src={CrashImage.src}
          alt=""
        />
        <div id="crash-info" className="flex flex-col justify-center p-6">
          <h5 className="mb-2 text-start text-xl font-medium text-gray-900">
            Crash / Boom Indices
          </h5>
          <p className="mb-4 text-start text-base text-gray-700">
            These indices observe an average of one drop (crash) or one spike
            (boom) in prices every 100 ticks.
          </p>
        </div>
      </div>

      <div
        id="card-volatility"
        className="flex flex-col rounded-lg bg-white shadow-black drop-shadow-2xl md:max-w-xl md:flex-row"
      >
        <img
          id="volatility-image"
          className="h-96 w-full rounded-t-lg object-cover md:h-auto md:w-48 md:rounded-none md:rounded-l-lg"
          src={VolatilityImage.src}
          alt=""
        />
        <div id="volatility-info" className="flex flex-col justify-center p-6">
          <h5 className="mb-2 text-start text-xl font-medium text-gray-900">
            Volatility Indices
          </h5>
          <p className="mb-4 text-start text-base text-gray-700">
            These indices are generated by in-house models to mimic the real
            market with constant volatilities of 10% and 25%.
          </p>
        </div>
      </div>
    </div>
  )
}
