import React from 'react'

export function CardProduct() {
  return (
    <div className="flex justify-between">
      <div className="flex flex-col rounded-lg bg-white shadow-md shadow-gray-800 md:max-w-xl md:flex-row">
        <img
          className=" h-96 w-full rounded-t-lg object-cover md:h-auto md:w-48 md:rounded-none md:rounded-l-lg"
          src="https://images.unsplash.com/photo-1530679361860-63f81c6e9268?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80"
          alt=""
        />
        <div className="flex flex-col justify-start p-6">
          <h5 className="mb-2 text-xl font-medium text-gray-900">
            Crash / Boom Indices
          </h5>
          <p className="mb-4 text-start text-base text-gray-700">
            These indices observe an average of one drop (crash) or one spike
            (boom) in prices every 100 ticks.
          </p>
        </div>
      </div>

      <div className="h-28 w-28"></div>

      <div className="flex flex-col rounded-lg bg-white shadow-md shadow-gray-800 md:max-w-xl md:flex-row">
        <div className="flex flex-col justify-start p-6">
          <h5 className="mb-2 text-xl font-medium text-gray-900">
            Volatility Indices
          </h5>
          <p className="mb-4 text-start text-base text-gray-700">
            These indices are generated by in-house models to mimic the real
            market with constant volatilities of 10% and 25%.
          </p>
        </div>
        <img
          className=" h-96 w-full rounded-t-lg object-cover md:h-auto md:w-48 md:rounded-none md:rounded-r-lg"
          src="https://images.unsplash.com/photo-1511909938134-66234e1aa5c9?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80"
          alt=""
        />
      </div>
    </div>
  )
}
